version: "3.8"

services:
  wpoms_admin:
    build: ./wpoms_admin
    container_name: wpoms_admin
    ports:
      - "8001:8000"

  wpoms_web:
    build: ./wpoms_web
    container_name: wpoms_web
    ports:
      - "8002:8000"